name: complyr-indexer
description: Indexer for Complyr on Sepolia ETH

field_selection:
  transaction_fields:
    - hash
    - from
    - input

networks:
  - id: 11155111
    rpc_config:
      url: https://ethereum-sepolia-rpc.publicnode.com
    start_block: 6000000
    contracts:
      - name: SmartWallet
        handler: src/EventHandlers.ts
        events:
          - event: Executed(address indexed target, uint256 value, bytes data)
          - event: ExecutedBatch(uint256 indexed batchSize, uint256 totalValue)
          - event: IntentBatchTransferExecuted(bytes32 indexed intentId, uint256 indexed transactionCount, uint256 recipientCount, uint256 totalValue, uint256 failedAmount)
          - event: IntentTransferSuccess(bytes32 indexed intentId, uint256 indexed transactionCount, address indexed recipient, uint256 amount)
          - event: TransferFailed(bytes32 indexed intentId, uint256 indexed transactionCount, address indexed recipient, uint256 amount)
          - event: WalletAction(address indexed initiator, address indexed target, uint256 value, bytes4 indexed selector, bool success, bytes32 actionType)
      - name: SmartWalletFactory
        handler: src/EventHandlers.ts
        events:
          - event: AccountCreated(address indexed account, address indexed owner)
      - name: IntentRegistry
        handler: src/EventHandlers.ts
        events:
          - event: IntentCreated(address indexed wallet, bytes32 indexed intentId, string name, address indexed token, uint256 totalCommitment, uint256 totalTransactionCount, uint256 interval, uint256 duration, uint256 transactionStartTime, uint256 transactionEndTime, address[] recipients, uint256[] amounts)
          - event: IntentExecuted(address indexed wallet, bytes32 indexed intentId, string name, uint256 transactionCount, uint256 totalAmount)
          - event: IntentCancelled(address indexed wallet, bytes32 indexed intentId, string name, uint256 amountRefunded, uint256 failedAmountRecovered)
      - name: MockUSDC
        handler: src/EventHandlers.ts
        events:
          - event: Transfer(address indexed from, address indexed to, uint256 value)
      - name: ComplianceRegistry
        handler: src/EventHandlers.ts
        events:
          - event: RecordAppended(address indexed proxyAccount, bytes32 indexed txHash, address[] recipients, uint256[] amounts, uint256[] categories, uint256[] jurisdictions, uint256 timestamp)
