name: complyr-indexer
description: Indexer for Complyr

field_selection:
  transaction_fields:
    - hash
    - from
    - input

networks:
  - id: 545
    rpc_config:
      url: https://testnet.evm.nodes.onflow.org
    start_block: 102148400
    contracts:
      - name: SmartWallet
        handler: src/EventHandlers.ts
        events:
          - event: Executed(address indexed target, uint256 value, bytes data)
          - event: ExecutedBatch(uint256 indexed batchSize, uint256 totalValue)
          - event: IntentBatchTransferExecuted(bytes32 indexed intentId, uint256 indexed transactionCount, uint256 recipientCount, uint256 totalValue, uint256 failedAmount)
          - event: IntentTransferSuccess(bytes32 indexed intentId, uint256 indexed transactionCount, address indexed recipient, uint256 amount)
          - event: TransferFailed(bytes32 indexed intentId, uint256 indexed transactionCount, address indexed recipient, uint256 amount)
          - event: WalletAction(address indexed initiator, address indexed target, uint256 value, bytes4 indexed selector, bool success, bytes32 actionType)
      - name: SmartWalletFactory
        address:
          - 0x6d39ae04c757ae3658c957b240835cc040923105
        handler: src/EventHandlers.ts
        events:
          - event: AccountCreated(address indexed account, address indexed owner)
      - name: IntentRegistry
        address:
          - 0x8bd539be7554752dc16b4d96ac857f3752b39cc1
        handler: src/EventHandlers.ts
        events:
          - event: IntentCreated(address indexed wallet, bytes32 indexed intentId, string name, uint256 totalCommitment, uint256 totalTransactionCount, uint256 interval, uint256 duration, uint256 transactionStartTime, uint256 transactionEndTime, address[] recipients, uint256[] amounts)
          - event: IntentExecuted(address indexed wallet, bytes32 indexed intentId, string name, uint256 transactionCount, uint256 totalAmount)
          - event: IntentCancelled(address indexed wallet, bytes32 indexed intentId, string name, uint256 amountRefunded, uint256 failedAmountRecovered)
